Editor: main.o pixels.o info.o filter_commander.o change_scale.o change_format.o bmp_header.o
	gcc main.o pixels.o info.o filter_commander.o change_scale.o change_format.o bmp_header.o -o Editor

main.o: main.c bmp_header.h info.h pixels.h change_scale.h change_format.h filter_commander.h main.h
	gcc -c main.c -o main.o

change_format.o: change_format.c change_format.h bmp_header.h main.h
	gcc -c change_format.c -o change_format.o

change_scale.o: change_scale.c change_scale.h main.h
	gcc -c change_scale.c -o change_scale.o

info.o:	info.c info.h
	gcc -c info.c -o info.o

filter_commander.o: filter_commander.c filter_commander.h main.h
	gcc -c filter_commander.c -o filter_commander.o

pixels.o: pixels.c pixels.h main.h
	gcc -c pixels.c -o pixels.o

bmp_header.o: bmp_header.c bmp_header.h main.h
	gcc -c bmp_header.c -o bmp_header.o
